### ISSUE TITLE
Possible infinite loop on RIFF content

### ISSUE THREAD

**Issue by Jubatian** [panzi/mediaextract#1]
Hi! Thanks for this useful little program, worked nice, however I had to patch it up a bit. So a bug report:

In the riff.c source, the riff_isfile routine may produce a zero in info->length. This causes the main program becomes stuck in an infinite loop (it doesn't increment the file pointer as far as I understood, this case).

Without giving much in understanding the program in-depth, I patched riff_isfile so it doesn't return TRUE (1) when "end - data" is zero (simply by adding one more condition in there). This worked for me, and feels somewhat appropriate since a zero length data just shouldn't match anything.

I can't quite give a sample to reproduce the bug since I used the program to burn through an entire HDD image (which got its file allocation tables wiped out), and had no much intention trying to isolate this. Hope the location of my patch gives enough clue for a proper fix.

**Comment by panzi** [comment]
I don't quite understand under what circumstance `data == end` could be true. Maybe there are some 32bit integer overflows? Hmm. An example file would be really helpful for a proper fix. Thanks to bring this to my attention anyway.

**Comment by panzi** [comment]
Did you compile it to a 32bit or 64bit binary? Because you said you scanned a hard disk, I guess 64bit?

**Comment by panzi** [comment]
What happens if you don't do your fix but instead replace all occurrences of `uint32_t chunk_size` with `size_t chunk_size` in `riff.c`? Does that also fix the problem?

**Comment by Jubatian** [comment]
(Huh, never expected a reaction this fast! :) ) Sorry, yes, it is a 64 bit system (Debian Linux). Your proposal seems to be working: the program with your suggested change proceed to write out a 4Gb file (wav, a definitely bogus match though) instead of getting stuck in an infinite loop complaining about finding a zero sized wav too small (due to constraining minimal size on command line).

I still get only a 2Gb file though, on an ext4 filesystem.

(EDIT: Bogus match... I don't blame the program for that, of course, on a HDD there could be anything. Fragmentation, deleted files, whatnot. As I checked, a wav header is there, just that there is apparently no related data following. File sizes this large are also quite beyond the intended uses, just noted)

**Comment by panzi** [comment]
Ok, that's then another problem. Could you post the first, I don't know, 1024 bytes or so of the wrongly extracted file somewhere (maybe 128 is enough)? Maybe I can find out why it's a false positive. Also I just released an update. I use `size_t` in more places no to avoid that kind of integer overflow.
