### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by abbabba21** [panzi/mediaextract#17]
Hello, I use the Windows 64bit binary from the official site because I'm not able to compile the last version.
I noticed that if I use _"--formats=all"_ the program extracts N .jpeg files but if I use _"--formats=jepg"_ the program often extracts much more .jpegs.
Obviously, in my tests, the input files are the same .
I think it's a strange behavior. Isn't it? Thank you.
P.S.: Could someone send me the last version of compiled Win64 binary? I'm not so good to get them out on my own. Thanks

**Comment by panzi** [comment]
`mediaextract` doesn't extract overlapping files. Meaning if any of the other formats apply before JPEG for a certain area of the archive file it won't try to extract that same area with JPEG. It already found something else! Maybe that is the case? Does it extract other files using `--formats=all`?

**Comment by abbabba21** [comment]
Yes, I used an hex editor to check and that's the reason. Thank you for the explaination.
If someone could give me an updated win64 binary I'll be super happy. Thank you again!

**Comment by panzi** [comment]
The 1.1 release zip already contains the latest 64 bit Windows build: https://github.com/panzi/mediaextract/releases/tag/v1.1

**Comment by abbabba21** [comment]
Thank you very much!
