### ISSUE TITLE
False detect on a stray RIFF chunk

### ISSUE THREAD

**Issue by Jubatian** [panzi/mediaextract#2]
So reflecting the other issue (https://github.com/panzi/mediaextract/issues/1), here is a chunk of binary data which looks like a WAV file, however in the reality there is no such content there. As far as checking in a hex editor, it definitely looks like a WAV header, and even sox tries to play it, detecting an almost 7 hours long content (this also applies to the source of the hexadump below, so it likely contains the problem).

```
00000000  52 49 46 46 f8 ff ff ff  57 41 56 45 66 6d 74 20  |RIFF....WAVEfmt |
00000010  10 00 00 00 01 00 02 00  44 ac 00 00 10 b1 02 00  |........D.......|
00000020  04 00 10 00 64 61 74 61  d4 ff ff ff 52 49 46 46  |....data....RIFF|
00000030  f8 ff ff ff 43 44 58 41  66 6d 74 20 10 00 00 00  |....CDXAfmt ....|
00000040  00 00 00 00 00 00 58 41  00 00 00 00 00 00 00 00  |......XA........|
00000050  64 61 74 61 d4 ff ff ff  18 00 18 00 50 32 01 00  |data........P2..|
00000060  02 00 02 00 4c 32 01 00  4e e6 40 bb b1 19 bf 44  |....L2..N.@....D|
00000070  20 05 93 19 00 00 00 00  00 00 00 00 00 00 00 00  | ...............|
```

I understand maybe this will just become a "wontfix" depending on what is actually in there (I didn't look in RIFF specs, so don't know), just posted it out of interest.

**Comment by panzi** [comment]
I take a closer look at this tomorrow, but maybe there is audio software that maxes out the size field during creation of a WAV file and only corrects it afterwards and you gut such an intermediate file there. That would be my guess anyway. Well, it isn't completely maxed out, but almost (f8 ff ff ff = 4294967288, max unsinged 32bit would be 4294967295).

**Comment by Jubatian** [comment]
Maybe. I don't have access to it now, but on decoding, I think there were several other occasions with small wav like contents which turned out not to be actual files. This one continues with some hundred bytes of zeros, then some unintelligible contents, absolutely not PCM audio (playing with sox produces "random" noise, hexadecimal data shows no human decipherable characteristics, and this starts within a kilobyte, certainly before any natural file system block size would be over). I don't know what these originally should have been. If interested, a few days from now I may be able to look in this matter and provide some other headers of apparent false positives.

The file system on the HDD image by the way likely has very little fragmentation as I could even extract some >50 meg continuous files (videos) from it, and in general nearly 100% of the apparent positive detects turned out to be completely intact files (including more than 5000 >100K jpeg images, and several mp3 files detected by ID3v2 composing full albums - so nearly all the mp3's relating to the observed albums seem to be retrieved intact).

(By the way jpeg at sizes about < 40K also produces astronomical quantities of false detects on this HDD image, if interested, maybe worth investigating in an another issue)

**Comment by panzi** [comment]
Hm, it might be a sparse file. Do the zeros end at a 4k boundary? That would support that theory. That's of course not possible to detect/handle without understanding the filesystem format.

**Comment by Jubatian** [comment]
I don't have the file here right now, but definitely no for that. I remember originally I wanted to post an 1K dump in which the "noise" already started. The file system is (was) NTFS on that disk (if you referred to that the file might have not started at a boundary, I don't know: I will need to check with your program again once I get back to my PC).

**Comment by Jubatian** [comment]
I checked it: almost true. The offset is 0xF8F91694 and the nonzero data after the chunk of zeroes in the file starts at 0x16C (beginning as 0x90, 0x90, 0x90, 0x90, 0x90, 0x8B, 0xFF, 0x55), so as absolute offset, at 0xF8F91800. This is a 2Kbyte boundary. I guess if the header otherwise is all right, there is nothing much to do here in this regard (the misdetection is not identifiable on this level).

**Comment by panzi** [comment]
Ok, so I close this issue.

**Comment by panzi** [comment]
Btw. I wrote a tiny tool that prepends a WAVE header to arbitrary files: https://github.com/panzi/wavhdr
You can use that to turn a memory dump into a wav file and then load it with something like audacity. Then simply seek to where you actually find some non-noise and cut that out. Note that while the default sample rate/bit rate/channels settings should usually work, you might need to play with them. I tested it and it did partially work with one game, although the voices in the game I tried seem somehow not end up in memory (or not more than a fraction of a second of them).

**Comment by Jubatian** [comment]
Seems interesting for some purposes, although limited (in size) as it needs a human ear to listen whether it is audio. To some degree it could be automated though: good audio data has no DC component (that is for example with unsigned 8 bit PCM averaging any longer than one second chunk should produce a result near 0x80), so such a test could filter out non-audio segments. For the game based on what you say it seems you tried to analyze memory captures. What you got might have been a buffer, and maybe the game never uncompresses any sample in whole anywhere, rather streams them directly from their uncompressed source, so you never get more than a few dozen milliseconds of raw audio data anywhere.
