### ISSUE TITLE
Extracting text omits the first character

### ISSUE THREAD

**Issue by Shmiddty** [panzi/mediaextract#23]
I'm extracting text (`-f text`) from a binary file and it appears that the first character is sometimes missing. 

eg: 
```xml
?xml version="1.0" encoding="UTF-8"?>
<map version="1.9" ...
```

This does not appear to happen when using a targeted text type eg `-f ascii`.

**Comment by panzi** [comment]
Is there another chunk of another text type wrongly detected before that chunk and saved as a separate file? The `-f text` option might not actually be really good and detect quite a bit bogus stuff in UTF-16 and UTF-32. I recommend to use `-f utf8` or `-f ascii`.

**Comment by Shmiddty** [comment]
That is likely the case. `-f ascii` worked for my use case.

**Comment by panzi** [comment]
Ok, great! I think I'll add a note about that. That it's better to use `utf-8` or `ascii` and not `text`.
