### ISSUE TITLE
[Feature request]: webm video format/container support

### ISSUE THREAD

**Issue by suphamster** [panzi/mediaextract#24]
Any chance to add it plz? Also would be nice to see avif images support too.

**Comment by panzi** [comment]
Oh, yeah, I think AVIF should be doable (I think it's more or less like RIFF). Never had a look at WebM, though, so I don't know if that is easy. Maybe when I have time and am not tired for a change I'll look into at least AVIF.

**Comment by suphamster** [comment]
As far as I know webm is very similar as mkv so maybe start from it if you want and switch to webm later.
Not sure if it would help but:
https://www.matroska.org/technical/elements.html
https://github.com/Matroska-Org/foundation-source

**Comment by panzi** [comment]
Yeah, I had a look at MKV once. It was too complicated to be fun, so I never implemented it.

**Comment by panzi** [comment]
Ok, implemented AVIF (and HEIF - which has basically the same container format) support.
