### ISSUE TITLE
extract to... smk

### ISSUE THREAD

**Issue by MatrixFr** [panzi/mediaextract#3]
C:\mediaextract-2015-03-13\build-win32>medi
aextract.exe --formats=all Army_Lose.smk
Extracting 0x00000000 ... 0x00333e4c (3.20271 MB) from Army_Lose.smk
Writing 3.20271 MB to .\Army_Lose.smk_00000000.smk
Extracted 1 file of 3.20271 MB size.

Why extract .smk to .smk? I need all files contains. What's wrong?

On winXP 32bit.

**Comment by panzi** [comment]
Well, a smk file contains exactly one smk file, so this is correct. But if you don't want to extract smk files try: `--formats=all,-smk`

**Comment by MatrixFr** [comment]
Hum... this only create .txt file of 1ko, so almost empty. No sound, no images, snif. Are you sure it's works?^^

**Comment by panzi** [comment]
What is it you want to do? I don't think smk files contain any other files. Do you want to play the video? I think ffmpeg can play smk files, which in turn means vlc should be able to play smk videos. Do you want to dump the frames of an smk file? You should be able to do that with ffmpeg/vlc, too.

**Comment by MatrixFr** [comment]
I thought images, sounds and vidéos are hidden in smk file...

What is the manipulation on VLC to dump frames?

EDIT: if I try read smk file with VLC, there is an error...

**Comment by panzi** [comment]
If vlc doesn't work, maybe ffmpeg works for you:

```
ffmpeg -i file.smk -f image2 frame%05d.png
```

Or maybe something like this with mencoder:

```
mencoder file.smk -vo jpeg:outdir=/path/to/some/dir
```

See `man ffmpeg` or `man mencoder`.
