### ISSUE TITLE
XMI support

### ISSUE THREAD

**Issue by tomas** [panzi/mediaextract#7]
Hi, this is a cool little tool! Any plans for including support for XMIDI (.xmi)? It's fairly similar to MIDI.

**Comment by panzi** [comment]
I could do that, but I'd need some example XMIDI files. Do you know where I can get some?

**Comment by tomas** [comment]
Eye of the Beholder III contains XMI files embedded within the EYE.RES file and others. [Here](http://www.vgmpf.com/Wiki/index.php?title=Eye_of_the_Beholder_III:_Assault_on_Myth_Drannor_%28DOS%29) you can download the extracted XMI files, and read a bit more about the way they were extracted.

**Comment by panzi** [comment]
Ok, implemented XMIDI support. Please test it if you can.

**Comment by tomas** [comment]
Wow! That was fast. 

Is mediaextract capable of reading through compressed or weirdly packaged files?

**Comment by panzi** [comment]
No, sorry. It can only scan uncompressed unfragmented unencrypted files. It just scans for the signatures of the known file formats and then tries to parse-out the whole media file.

**Comment by tomas** [comment]
Can I pipe something into it, then? Like:

`tar xf package.tar.gz | mediaextract -f all -o /destination`

That would allow building a wrapper that could identify compressed files and process them too.

**Comment by panzi** [comment]
mediaextract uses mmap, so no piping I'm afraid.
